# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_QL4LKcUQCsQLJsgQa5LCbmPYTaSixg
"""

# entrada
notas = [None for i in range(50)]
notas_id = 0

# menu principal
def print_menu():
    print("="*30)
    print("Controle de Notas dos Alunos")
    print("-"*30)
    print("Menu: ")
    print("-"*30)
    print("1 - Inserir Nota")
    print("2 - Média da Turma")
    print("3 - Menor Nota")
    print("4 - Maior Nota")
    print("5 - Sair")
    print("="*30)

# inserir nova nota
def inserir_nota(nova_nota):
    global notas_id
    if notas_id < 50:
        notas[notas_id] = nova_nota
        notas_id += 1
        print(f"\nNota {nova_nota} inserida com sucesso!\n")
    else:
        print("Limite de 50 alunos atingido!")

# definir maior e menor nota
def nota_min(array):
    guardadas = [nota for nota in array if nota is not None]
    return min(guardadas) if guardadas else None

def nota_max(array):
    guardadas = [nota for nota in array if nota is not None]
    return max(guardadas) if guardadas else None

# loop
while True:
    print_menu()
    opt = input("\nEscolha uma opção: ")

    match opt:
        case "1":
            try:
                valor = float(input("\nDigite a nota do aluno (0 a 10): "))
                if 0 <= valor <= 10:
                    inserir_nota(valor)
                else:
                    print("\nNota inválida! Digite um valor entre 0 e 10.")
            except ValueError:
                print("\nNota inválida! Digite apenas números entre 0 e 10.")

        case "2":
            if notas_id > 0:
                soma = 0.0
                i = 0
                while i < notas_id:
                    soma += notas[i]
                    i += 1

                media = soma / notas_id
                print(f"\nMédia da turma: {media:.2f}")
            else:
                print("\nNenhuma nota cadastrada.")

        case "3":
            menor = nota_min(notas)
            if menor is not None:
                print(f"\nMenor nota da turma: {menor:.2f}\n")
            else:
                print("\nNenhuma nota cadastrada.\n")

        case "4":
            maior = nota_max(notas)
            if maior is not None:
                print(f"\nMaior nota da turma: {maior:.2f}\n")
            else:
                print("\nNenhuma nota cadastrada.\n")

        case "5":
            print("\nEncerrando o programa...")
            break

        case _:
            print("\nOpção inválida! Escolha um número de 1 a 5.")